### ISSUE TITLE
提几个问题

### ISSUE THREAD

**Issue by 0RaymondJiang0** [TheodoreKrypton/JavPy#46]
我的环境是，Python3.5 ，前后端安装正常。但运行有几个问题：
1. main.py 应该移到项目根路径下面，不应该放到里面的 JavPy目录，不然使用 python ./main.py 无法启动项目。
2. 有一个bug , 在 check_request 方法内部，没有检查 request.data 是否有值，这个地方如果是空字符串，会导致decode的500错误。这个错误几乎能稳定重现。
![image](https://user-images.githubusercontent.com/501182/59004519-71398d80-884c-11e9-96e7-fe1ae8f709fd.png)
如上修改后，问题解决。
3. 前端这个地方，由于使用了 vue 路由的 history模式，导致手动刷新页面会到后端去请求页面，就导致了404的问题，当然如果部署时在nginx配置一下，该问题可以解决，但是开发环境调试就很不方便，特别是输入密码后的跳转，会直接导致404。这个地方，应该可以在前端修改一下配置，或者索性搞成 hash模式。

**Comment by TheodoreKrypton** [comment]
谢谢建议！

main.py是我调试的时候使用的，我预想的使用方法是
pip install JavPy

import JavPy
JavPy.serve()
但是我会加上直接clone后运行的方法

第二个bug我回去看一下，感谢提醒

第三个主要是因为flask在没匹配到路径的时候会直接返回404，不会转发给前端去处理，已经在下个版本中解决。我对Vue这一块还不太熟悉，哈哈

0RaymondJiang0 <notifications@github.com>于2019年6月6日 周四上午11:15写道：
