### ISSUE TITLE
如何设置密码？

### ISSUE THREAD

**Issue by xdx3000** [TheodoreKrypton/JavPy#53]
运行起来后，没有设置密码的情况下，打开页面时反复要求我输入密码。不论用空密码，还是输入其他什么，窗口都始终挡在前面，无法使用。

当我试图在config.json中，当我试图设置密码："password": "1"，然后访问网址，就会报错raise ValueError("No JSON object could be decoded")，报500错误。密码究竟应该如何设置？或者如何跳过密码？

**Comment by TheodoreKrypton** [comment]
直接点击Confirm即可，没有写清楚不好意思

**Comment by vincentkwang** [comment]
你好
我已经重复点击了确认还是无法登入。请问如何跳过密码？

**Comment by TheodoreKrypton** [comment]
> 你好
> 我已经重复点击了Confirm还是无法登入。请问如何跳过密码？

请问之前在config.json中设置过密码吗？没有设置过，点击Confirm无法跳过的话，可以提供浏览器和Python版本，我稍后做个测试。

**Comment by vincentkwang** [comment]
> > 你好
> > 我已经重复点击了Confirm还是无法登入。请问如何跳过密码？
> 
> 请问之前在config.json中设置过密码吗？没有设置过，点击Confirm无法跳过的话，可以提供浏览器和Python版本，我稍后做个测试。

没有在config.json中设置任何密码。
浏览器版本是safari 12.1.2与chrom 76.0.3809.132
上述两种浏览器都无法跳过密码。

**Comment by xdx3000** [comment]
> 
> 
> @xdx3000 @vincentkwang 我刚才测试了Python2.7和Python3.6的最新版本，浏览器用的Chrome 76.0.3809.132 64位，没有发现异常，是不是在控制台输入javpy后将控制台关掉了？注意输入完命令请不要关掉后台。如果没有的话，可以将控制台的输出发给我看一下吗？

[root@myserver ~]# python -c "import JavPy; JavPy.serve()"

                       __            ____
                      / /___ __   __/ __ \__  __
                 __  / / __ `/ | / / /_/ / / / /
                / /_/ / /_/ /| |/ / ____/ /_/ /
                \____/\__,_/ |___/_/    \__, /
                                       /____/

    Awesome! Now try to type
        JavPy.serve()
    and open http://localhost:8081 to enjoy driving!

    If you want to run a telegram bot server, instead, please type
        JavPy.serve_tg(token)
    But please get a token from the bot father first

    Advanced usage: JavPy.hlp()
    More info: https://github.com/theodorekrypton/JavPy

 * Serving Flask app "JavPy.app.webserver.app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:8081/ (Press CTRL+C to quit)
220.250.18.194 - - [14/Sep/2019 00:12:00] "GET / HTTP/1.1" 200 -
220.250.18.194 - - [14/Sep/2019 00:12:03] "GET /css/chunk-vendors.24c39596.css HTTP/1.1" 200 -
220.250.18.194 - - [14/Sep/2019 00:12:03] "GET /css/app.e3b785b6.css HTTP/1.1" 200 -
220.250.18.194 - - [14/Sep/2019 00:12:03] "GET /js/app.702b5a83.js HTTP/1.1" 200 -
220.250.18.194 - - [14/Sep/2019 00:12:05] "GET /js/chunk-vendors.aa4014a6.js HTTP/1.1" 304 -
220.250.18.194 - - [14/Sep/2019 00:12:11] "GET /img/logo.7906e173.png HTTP/1.1" 200 -
220.250.18.194 - - [14/Sep/2019 00:12:11] "GET /fonts/element-icons.535877f5.woff HTTP/1.1" 200 -

此时我点击confirm，没有更多输出产生。

**Comment by vincentkwang** [comment]
使用了chrome & safari的开发人员工具，都有显示"auth_by_password failed"的错误

**Comment by TheodoreKrypton** [comment]
@xdx3000 @vincentkwang 刚刚fix了密码错误的一个问题，能再试着更新一下吗？或者能不能提供一下JavPy的版本号呢？

**Comment by TheodoreKrypton** [comment]
> @xdx3000 @vincentkwang 刚刚fix了密码错误的一个问题，能再试着更新一下吗？或者能不能提供一下JavPy的版本号呢？

`pip install -U JavPy` 即可

**Comment by vincentkwang** [comment]
> > @xdx3000 @vincentkwang 刚刚fix了密码错误的一个问题，能再试着更新一下吗？或者能不能提供一下JavPy的版本号呢？
> 
> `pip install -U JavPy` 即可

Requirement already up-to-date: JavPy in /usr/local/lib/python2.7/dist-packages (0.2.17)

**Comment by xdx3000** [comment]
> 
> 
> > @xdx3000 @vincentkwang 刚刚fix了密码错误的一个问题，能再试着更新一下吗？或者能不能提供一下JavPy的版本号呢？
> 
> `pip install -U JavPy` 即可

感谢回复。我更新之后也还是遇到一样的问题。似乎问题并没有得到解决。

**Comment by TheodoreKrypton** [comment]
@xdx3000 @vincentkwang 如果服务并非部署在本地，请将自己的网段放在config.json中的ip-whitelist中，之前没有注意看到输出的ip地址。默认的ip白名单有"127.0.0.1", "10.0.0.0/8", "172.16.0.0/12","192.168.0.0/24"。后续我会在readme中补上。这里主要是为了公网部署的安全访问做考虑。如果允许所有ip访问，请将whitelist改为"0.0.0.0/0"

**Comment by yxHenry** [comment]
问题可能在于你的前端部分config.js，应该把地址根据环境做个区分，服务器上的接口还在请求127.0.0.1
![image](https://user-images.githubusercontent.com/28614793/65829293-8d1ede80-e2d6-11e9-91c3-d21d2b020a52.png)

**Comment by xdx3000** [comment]
> 
> 
> @xdx3000 @vincentkwang 如果服务并非部署在本地，请将自己的网段放在config.json中的ip-whitelist中，之前没有注意看到输出的ip地址。默认的ip白名单有"127.0.0.1", "10.0.0.0/8", "172.16.0.0/12","192.168.0.0/24"。后续我会在readme中补上。这里主要是为了公网部署的安全访问做考虑。如果允许所有ip访问，请将whitelist改为"0.0.0.0/0"

这个我已经添加了，问题依旧
